name: main
on:
  push:
    branches:
      - main
jobs:
  main:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # yarn install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test --coverage
      - uses: codecov/codecov-action@v2
      - name: Build
        run: |
          mkdir -p dist
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: dist
    strategy:
      matrix:
        node:
          - lts/erbium
          - node

